gOtherText_NewName:: @ 81C574F
    .string "NEW NAME$"

gNameChoice_Green:: @ 81C5758
    .string "GREEN$"

gNameChoice_Red:: @ 81C575E
    .string "RED$"

gNameChoice_Leaf:: @ 81C5762
    .string "LEAF$"

gNameChoice_Fire:: @ 81C5767
    .string "FIRE$"

gNameChoice_Gary:: @ 81C576C
    .string "GARY$"

gNameChoice_Kaz:: @ 81C5771
    .string "KAZ$"

gNameChoice_Toru:: @ 81C5775
    .string "TORU$"

gNameChoice_Ash:: @ 81C577A
    .string "ASH$"

gNameChoice_Kene:: @ 81C577E
    .string "KENE$"

gNameChoice_Geki:: @ 81C5783
    .string "GEKI$"

gNameChoice_Jak:: @ 81C5788
    .string "JAK$"

gNameChoice_Janne:: @ 81C578C
    .string "JANNE$"

gNameChoice_Jonn:: @ 81C5792
    .string "JONN$"

gNameChoice_Kamon:: @ 81C5797
    .string "KAMON$"

gNameChoice_Karl:: @ 81C579D
    .string "KARL$"

gNameChoice_Taylor:: @ 81C57A2
    .string "TAYLOR$"

gNameChoice_Oscar:: @ 81C57A9
    .string "OSCAR$"

gNameChoice_Hiro:: @ 81C57AF
    .string "HIRO$"

gNameChoice_Max:: @ 81C57B4
    .string "MAX$"

gNameChoice_Jon:: @ 81C57B8
    .string "JON$"

gNameChoice_Ralph:: @ 81C57BC
    .string "RALPH$"

gNameChoice_Kay:: @ 81C57C2
    .string "KAY$"

gNameChoice_Tosh:: @ 81C57C6
    .string "TOSH$"

gNameChoice_Roak:: @ 81C57CB
    .string "ROAK$"

gNameChoice_Omi:: @ 81C57D0
    .string "OMI$"

gNameChoice_Jodi:: @ 81C57D4
    .string "JODI$"

gNameChoice_Amanda:: @ 81C57D9
    .string "AMANDA$"

gNameChoice_Hillary:: @ 81C57E0
    .string "HILLARY$"

gNameChoice_Makey:: @ 81C57E8
    .string "MAKEY$"

gNameChoice_Michi:: @ 81C57EE
    .string "MICHI$"

gNameChoice_Paula:: @ 81C57F4
    .string "PAULA$"

gNameChoice_June:: @ 81C57FA
    .string "JUNE$"

gNameChoice_Cassie:: @ 81C57FF
    .string "CASSIE$"

gNameChoice_Rey:: @ 81C5806
    .string "REY$"

gNameChoice_Seda:: @ 81C580A
    .string "SEDA$"

gNameChoice_Kiko:: @ 81C580F
    .string "KIKO$"

gNameChoice_Mina:: @ 81C5814
    .string "MINA$"

gNameChoice_Norie:: @ 81C5819
    .string "NORIE$"

gNameChoice_Sai:: @ 81C581F
    .string "SAI$"

gNameChoice_Momo:: @ 81C5823
    .string "MOMO$"

gNameChoice_Suzi:: @ 81C5828
    .string "SUZI$"

gNewGame_HelpDocs1:: @ 81C582D
    .string "The various buttons won't be explained.\n"
    .string "Deal with it...$"

gNewGame_HelpDocs2:: @ 81C5875
    .string "Who knows what this does.\n"
    .string "Why don't you try it out.$"

gNewGame_HelpDocs3:: @ 81C58BA
    .string "There's only so many buttons,\n"
    .string "experiment a little...$"

gNewGame_HelpDocs4:: @ 81C58F9
	.string "We aren't here to coddle\n"
	.string "you...$"

gNewGame_HelpDocs5:: @ 81C592B
    .string "Blah blah blah...$"

gNewGame_HelpDocs6:: @ 81C594F
    .string "Instructions are useless!$"

gNewGame_HelpDocs7:: @ 81C5981
    .string "If you need help playing the\n"
    .string "game, then just stop!$"

gOakText_AskPlayerGender:: @ 81C59D5
    .string "Now tell me. Are you a boy?\n"
    .string "Or are you a girl?$"

gNewGameAdventureIntro1::
    .string "In the hell which you are about to\n"
    .string "enter, you will embark on a slog\n"
    .string "of misery with you as the victim.\n"
    .string "\n"
    .string "Speak to people and check things\n"
    .string "wherever you go, be it towns, roads,\n"
    .string "or caves. Gather information and\n"
    .string "hints from every source.$"

gNewGameAdventureIntro2::
    .string "New paths will open to you by beating\n"
    .string "people in need, surviving battles,\n"
    .string "and brute force.\n"
    .string "\n"
    .string "Always, you will be challenged by\n"
    .string "others and attacked by wild creatures.\n"
    .string "Give up now and submit.$"

gNewGameAdventureIntro3::
    .string "Through your adventure, we hope\n"
    .string "that you will interact with all sorts\n"
    .string "of demons and achieve personal loss.\n"
    .string "That is our biggest objective.\n"
    .string "\n"
    .string "Press the A Button, and let your\n"
    .string "misery begin!$"

gOakText_WelcomeToTheWorld:: @ 81C5C78
    .string "GO AWAY!\n"
    .string "Let's get this over with!\pWelcome to the hell of POKéMON!\pMy name is LUCIFER.\pPeople refer to me\n"
    .string "as the POKéMON DEVIL.\p$"

gOakText_WorldInhabited1:: @ 81C5D06
    .string "This world…$"

gOakText_WorldInhabited2:: @ 81C5D12
    .string "…is inhabited far and wide by\n"
    .string "creatures called POKéMON.\p$"

gOakText_PetsBattlingStudy:: @ 81C5D4B
    .string "For some people, POKéMON are pets.\n"
    .string "Others use them for battling.\pAs for myself…\pI gamble on POKéMON fights.\p$"

gOakText_TellMeALittleAboutYourself:: @ 81C5DBD
    .string "Let's fill out the forms...$"

gOakText_AskPlayerName:: @ 81C5DEA
    .string "What's your name kid?$"

gOakText_FinalizePlayerName:: @ 81C5E13
    .string "Right…\n"
    .string "So your name is {PLAYER}.$"

gOakText_IntroduceRival:: @ 81C5E2E
    .string "This is my buddy.\pHe's here to make sure you lose.\n"
    .string "Their name is none of your business!$"

gOakText_AskRivalName:: @ 81C5E91
    .string "Fine! Name'em!$"

gOakText_ConfirmRivalName:: @ 81C5EB5
    .string "Really?!? {RIVAL}?$"

gOakText_RememberRivalName:: @ 81C5EC5
    .string "Whatever... Their name is...\n"
    .string "{RIVAL}!\p$"

gOakText_LegendAboutToUnfold:: @ 81C5EF4
    .string "{PLAYER}!\pthanks for being a chump!\n"
    .string "I'll be betting against ya everytime!\n"
    .string "Now go make me some money!$"
